### ISSUE TITLE
repo.yaml is missing in cloudpak4data*.tgz archives (version 3.0.1-1)

### ISSUE THREAD

**Issue by jensmueller-com** [IBM/cpd-cli#15]
According to the [IBM Cloud Pak for Data 3.0.1 documentation](https://www.ibm.com/support/knowledgecenter/SSQNUZ_3.0.1/cpd/install/installation-files.html), all `cloudpak4data*.tgz` files should contain a file named `repo.yaml`:

```
A bin folder is created in the current directory with the cpd command binaries and a repo.yaml.
```

However, in contrast to the initial release (3.0.1), the `cloudpak4data*.tgz` archives of the latest release (3.0.1-1) do not contain this YAML file anymore.

**Comment by bmat7717** [comment]
I have seen the same with another client.

**Comment by dianadujing** [comment]
Same here. @guptadiv

**Comment by guptadiv** [comment]
@jensmueller-com @dianadujing Added the repo.yamls to the tar archives
