### ISSUE TITLE
*.tgz archives are plain tar files and contain ._* files (version 3.5.0)

### ISSUE THREAD

**Issue by jensmueller-com** [IBM/cpd-cli#19]
There are two issues with the `tgz` assets associated with the 3.5.0 release:

1. The `tgz` files are not gzip-compressed tar files but uncompressed tar files. While macOS still uncompresses them even if they are treated as compressed (`tar -xzf`), at least older tar versions on Linux complain when using this command:

```
$ tar -xzf cpd-cli-linux-EE-3.5.1.tgz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Therefore, either the file extension should be renamed to `.tar` or the tar files should be really compressed. The current file extension is misleading.

2. The six `tgz` files for darwin, linux, and ppc64le contain an additional `._*` file for each file/directory contained in the tar file. (the `tgz` files for s390x are fine) These files are produced by macOS and contain extended attributes. Here is an example of the `cpd-cli-darwin-EE-3.5.1-145/plugins/config` folder contained in `cpd-cli-darwin-EE-3.5.1.tgz`:

```
-rw-r--r-- 1 501 games  212 Oct 28 16:12 ._backup-restore.yaml
-rw-r--r-- 1 501 games  212 Oct 21 17:29 ._config.yaml
-rw-r--r-- 1 501 games  212 Nov  9 14:01 ._cpd-base.yaml
-rw-r--r-- 1 501 games  212 Oct 23 16:48 ._export-import.yaml
-rw-r--r-- 1 501 games  212 Oct 21 17:31 ._service-instance.yaml
-rw-r--r-- 1 501 games  346 Oct 28 16:12 backup-restore.yaml
-rw-r--r-- 1 501 games  283 Oct 21 17:29 config.yaml
-rw-r--r-- 1 501 games 1645 Nov  9 14:01 cpd-base.yaml
-rw-r--r-- 1 501 games  350 Oct 23 16:48 export-import.yaml
-rw-r--r-- 1 501 games  373 Oct 21 17:31 service-instance.yaml
```

When running `cpd-cli`, these `._*` files produce the following warnings:

```
[…] Unable to process plugin config file: /root/.dg/bin/cpd-3-5-0/plugins/config/._backup-restore.yaml
yaml: control characters are not allowed
[…] Unable to process plugin config file: /root/.dg/bin/cpd-3-5-0/plugins/config/._config.yaml
yaml: control characters are not allowed
[…] Unable to process plugin config file: /root/.dg/bin/cpd-3-5-0/plugins/config/._cpd-base.yaml
yaml: control characters are not allowed
[…] Unable to process plugin config file: /root/.dg/bin/cpd-3-5-0/plugins/config/._export-import.yaml
yaml: control characters are not allowed
[…] Unable to process plugin config file: /root/.dg/bin/cpd-3-5-0/plugins/config/._service-instance.yaml
yaml: control characters are not allowed
```

Therefore, I would suggest to recreate these six tar files (and compress them) without any `._*` files.

**Comment by guptadiv** [comment]
Issue resolved, closing now
