### ISSUE TITLE
panic error with `cpd-cli adm --accept-all-licenses`

### ISSUE THREAD

**Issue by johandry** [IBM/cpd-cli#25]
When executing `cpd-cli adm`, version 3.5.1, in a container and using the flag `--accept-all-licenses` we get the following panic error. 

This is happening when `cpd-cli` is executed by Schematics. We cannot choose how to run the container because it's executed by the Schematics Workspace runtime.

Error:
```
 [INFO] [2021-01-06 19:41:08-0792] Accepting license for this package
 panic: open /dev/tty: no such device or address

 goroutine 1 [running]:
 log.Panicln(0xc00088e4b0, 0x1, 0x1)
 	/opt/go/src/log/log.go:365 +0xac
 github.ibm.com/privatecloud/icpd_courier/cmd.displayLicense(0xc00081fa80, 0x1d, 0xc0007d25b0)
 	/root/workspace/cpd-v3.5.0/github.ibm.com/privatecloud/icpd_courier/cmd/license.go:45 +0x86
 github.ibm.com/privatecloud/icpd_courier/cmd.acceptPackageLicenses(0xc0007d23f0, 0x67, 0x0, 0x0)
 	/root/workspace/cpd-v3.5.0/github.ibm.com/privatecloud/icpd_courier/cmd/preinstallutils.go:630 +0x4ef
 github.ibm.com/privatecloud/icpd_courier/cmd.parseEntireAssembly(0xc00035a5a0, 0x1, 0x1, 0xc00028df60, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc00050f680, ...)
 	/root/workspace/cpd-v3.5.0/github.ibm.com/privatecloud/icpd_courier/cmd/preinstallutils.go:114 +0x24ae
 github.ibm.com/privatecloud/icpd_courier/cmd.adm(0x1ea0000, 0xc0002a58c0)
 	/root/workspace/cpd-v3.5.0/github.ibm.com/privatecloud/icpd_courier/cmd/adm.go:223 +0x28e
```

The error is not happening when `cpd-cli` is executed from a computer. Neither happened with version 3.0. This is a bug introduced in version 3.5.x

**Comment by kandaaaaa** [comment]
@johandry Will run without the flag `--accept-all-licenses` works? Which OS you are running on? Mac, linux or Windows?

**Comment by johandry** [comment]
We are running this on IBM Cloud Schematics, which is (or assume it is) a Linux container, but don't know which one.

If I run it without `--accept-all-licenses` it will ask me to accept the licenses, right? If so, there is no way I can do that as a user, this process is running by Schematics in a container.

**Comment by kandaaaaa** [comment]
@johandry please double-check the flag `--accept-all-licenses` you used. I looked at the code and it seems that if you specify the flag, you will not reach the line
```
[INFO] [2021-01-06 19:41:08-0792] Accepting license for this package
```
Instead, you should see https://github.ibm.com/PrivateCloud/icpd_courier/blob/cp4d-v3.5.1/cmd/preinstallutils.go#L97-L98

**Comment by guptadiv** [comment]
@johandry please reopen if this issue is still valid
