### ISSUE TITLE
Something wrong w/ Darwin EE tgz

### ISSUE THREAD

**Issue by tknorris** [IBM/cpd-cli#28]
FYI, something seems wrong w/ the cpd-cli file in the 3.5.2 Darwin EE release of cpd-cli. The cpd-cli file in the tgz file is also a .tar.gz file itself and that file then seems to contain a new set of plugins/ and LICENCES, but no cpd-cli file thus making it unusable.

**Comment by guptadiv** [comment]
@tknorris We had to repackage it, please try now

**Comment by tknorris** [comment]
confirmed fixed
