### ISSUE TITLE
/cpd-cli: cannot execute binary file

### ISSUE THREAD

**Issue by Kleberfs75** [IBM/cpd-cli#30]
Downloading the fille cpd-cli-darwin-EE-3.5.2.tgz to my MAC OS : Big Sur 11.1 and extracting it by tar xvf cpd-cli-darwin-EE-3.5.2.tgz , I tried run the command ./cpd-cli and the error was shown:
./cpd-cli: cannot execute binary file

**Comment by guptadiv** [comment]
@Kleberfs75 We had to repackage it, please try now
