### ISSUE TITLE
Incorrect Operating system title for Linux on Z on the IBM cloud Pak for data Installer Readme page

### ISSUE THREAD

**Issue by johnottogood** [IBM/cpd-cli#33]
The installation files for s390 Linux is described as z/OS operating system 

You probably should use some form of Linux on x86 and Linux on Z to distinguish the two Linux operating systems.   Calling the s390x Linux install file z/OS is not right.

![image](https://user-images.githubusercontent.com/24763563/110897821-26279680-82cc-11eb-9785-e5c41eff18cd.png)

**Comment by guptadiv** [comment]
Corrected after review from Doc team thanks
