### ISSUE TITLE
v3.5.3 release for ppce64le still pointing to version 3.5.2

### ISSUE THREAD

**Issue by imsanjeevi** [IBM/cpd-cli#34]
The v3.5.3 release for ppce64le (https://github.com/IBM/cpd-cli/releases/download/v3.5.3/cpd-cli-ppc64le-EE-3.5.3.tgz)
still pointing to version 3.5.2

tar -xvf cpd-cli-ppc64le-EE-3.5.3.tgz
 ./cpd-cli version
cpd-cli
        Version: 1.3.0
        Build Date: 2021-03-15T09:07:15
        Build Number: 6
        CPD Release Version: 3.5.2

**Comment by sprior** [comment]
I am affected by this as well, any ETA on a fix?

**Comment by guptadiv** [comment]
Showing CPD Release Version: 3.5.2 is correct, this is the cpd release version, which we didn’t have a refresh since Jan. Each plugin has it’s own version, i.e. cpd-cli is 1.3.0.
